### ISSUE TITLE
Allow non random times for the wipe and rebuild

### ISSUE THREAD

**Issue by MrShark** [bjarkef/wipe-workspace-plugin#2]
It would be useful to configure the rebuild time better. For some projects we have full rebuild times in the 8 hour range (don't ask, you don't want to know :crying_cat_face:) and it would be nice to clean them only once a week.

I would suggest exposing a crontype configuration (and if empty use the random approach for fall back). Will try to do it and issue a pull request, but my java/jenkins/maven-fo is weak I'm not sure it will materialize.

**Comment by bjarkef** [comment]
That would be a nice improvement. :+1:

**Comment by MrShark** [comment]
I have written some code to implement this in the branch here: https://github.com/MrShark/wipe-workspace-plugin
It still lacks persisting of the config which makes it somewhat unuseful, but hopefully I will get to that and will then issue a pull request.
